server:
  port: 9200
  servlet:
    context-path: /maganerProject
spring:
  application:
    name: service-proyects
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      
